name: frappe_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.0+8

environment:
    sdk: '>=2.12.0 <3.0.0'


dependencies:
  flutter_js: ^0.5.0+3
  device_preview: ^0.7.4
  flutter_secure_storage: ^4.2.1
  flutter_mentions: ^2.0.1
  photo_view: ^0.12.0
  flutter_easyloading: ^3.0.0
  html_editor_enhanced: ^2.3.0
  flutter_typeahead: ^3.1.1
  flutter_chips_input: ^1.10.0
  timelines: ^0.1.0
  persistent_bottom_nav_bar: ^4.0.2
  overflow_view: ^0.3.1
  injectable:
  json_table: ^2.0.1
  barcode_widget: ^2.0.1
  shared_preferences: ^2.0.5
  crypto: ^3.0.1
  device_info: ^2.0.0
  flutter_local_notifications: ^8.2.0
  # workmanager: ^0.4.0
  get_it: ^7.2.0
  fluttertoast: ^8.0.4
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  connectivity: ^3.0.3
  provider: ^5.0.0
  open_file: ^3.1.0
  flutter_svg: ^0.22.0
  collection: ^1.15.0
  cached_network_image: ^3.0.0
  google_fonts: ^2.0.0
  file_picker: ^4.0.2
  flutter_form_builder: ^7.0.0
  form_builder_validators: ^7.1.0
  flutter_pagewise: ^2.0.1
  html: ^0.15.0
  url_launcher: ^6.0.3
  permission_handler: ^8.1.6
  flutter_downloader: ^1.6.0
  timeago: ^3.0.2
  path_provider: ^2.0.1
  flutter_html: ^2.0.0
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  intl: ^0.17.0
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner:
  injectable_generator:
  hive_generator: ^1.0.1
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/frappe_icon.jpg"

dependency_overrides:
  flutter_colorpicker: ^0.6.0
  json_table:
    git:
      url: https://github.com/sumitbhanushali/json_table
      ref: 0eee306ab5338340cd63749d3dcfbdd4a5382885


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/icons/
   - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
